"""sync model with database

Revision ID: 5d890fab96a2
Revises: 96d358f09f76
Create Date: 2024-12-02 23:46:45.572662

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d890fab96a2"
down_revision: Union[str, None] = "96d358f09f76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blocks", sa.Column("user_id", sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blocks", "user_id")
    # ### end Alembic commands ###
