"""deleted workspace table

Revision ID: 863c8068530a
Revises: 44689ba11892
Create Date: 2024-12-04 12:39:10.376335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "863c8068530a"
down_revision: Union[str, None] = "44689ba11892"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workspaces")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspaces",
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("block_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"], ["blocks.id"], name="workspaces_block_id_fkey"
        ),
        sa.PrimaryKeyConstraint("owner_id", "id", name="workspaces_pkey"),
    )
    # ### end Alembic commands ###
