"""Add

Revision ID: 8c79e42c63ba
Revises: 1482e67c3043
Create Date: 2024-12-03 19:48:03.802428

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c79e42c63ba"
down_revision: Union[str, None] = "1482e67c3043"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("block_id", sa.UUID(), nullable=True))
    op.create_foreign_key(None, "workspaces", "blocks", ["block_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces", type_="foreignkey")
    op.drop_column("workspaces", "block_id")
    # ### end Alembic commands ###
